services:

  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./settings:/app/settings
    environment:
      - DOMAIN=my-domain.com

  mongo:
    image: mongo:6.0.8
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
